#define IDENTIFIER      1
#define INTEGER_LITERAL 2
#define FLOAT_LITERAL   3
#define INT             10
#define FLOAT           11
#define IF              12
#define ELSE            13
#define FOR             14
#define WHILE           15
#define RETURN          20
#define OPERATOR        30
#define LOGICAL_AND     31
#define LOGICAL_OR      32
#define EQUAL           33
#define NOT_EQUAL       34
#define LEFT_PAREN      40
#define RIGHT_PAREN     41
#define LEFT_BRACE      42
#define RIGHT_BRACE     43
#define SEMICOLON       50
#define COMMA           51
#define COLON           52

#define TWO_WAY_CLASSIFICATION_MODEL 300
#define ALPHABET 301
#define SYMBOL 302
#define STRING 303
#define STREAK 304
#define CATEGORY 305

#define MULTICOTOMIZE        400
#define COUNT_CHANGE         401
#define STREAK_NUMBER        402
#define TOTAL_DATA_MODEL     403
#define TOTAL_DATA_BLOCK     404
#define TOTAL_DATA_TREATMENT 405
#define GET_TOTAL_DATA       406
#define GET_BLOCK_DATA       407
#define GET_TREATMENT_DATA   408
